### ISSUE TITLE
Class and other <a> attributes for <router-link />

### ISSUE THREAD

**Issue by jesse1983** [charlieduong94/marko-path-router#14]
Hi.

I need add a css class for <router-link />, for example, this:

`<router-link.btn path='/users' rel="nofollow"> Go to users </router-link>`

Would render this:

`<a class="btn" href="/users" rel="nofollow"> Go to users </a>`

Is possible?

**Comment by charlieduong94** [comment]
Hello @jesse1983, thanks for creating this issue. I just published version `0.0.4` containing https://github.com/charlieduong94/marko-path-router/commit/1db0033eb65892b31ae9bf2c11907d533cc98ccf, which adds support for  passing along css classes like in your example.
