### ISSUE TITLE
routerComponent.on is not a function

### ISSUE THREAD

**Issue by VojtechKlos** [charlieduong94/marko-path-router#21]
Hello.

When trying to get the not-found event to work I got this error:

TypeError: routerComponent.on is not a function

My code is here:

`
const render = Router.renderSync({
		initialRoute: initRoute,
		routes: rootRoutes
	});

	const routerComponent = render.appendTo(document.body);

	routerComponent.on('not-found', () => {
		console.log('not found');
	});
`

Without the listener everything works fine.

Am I doing something wrong? Thanks for your help.

**Comment by austinkelleher** [comment]
I think what you want to do is:

```marko
const routerComponent = render.appendTo(document.body).getComponent();

routerComponent.on('not-found', () => {
	console.log('not found');
});
```

**Comment by charlieduong94** [comment]
Yep, like @austinkelleher said, you need to call `getComponent` after appending the router to the document body.

**Comment by VojtechKlos** [comment]
Thanks guys for the quick replies. Works now ;-)
