### ISSUE TITLE
Allowing "beforeEnter" hook to a router path

### ISSUE THREAD

**Issue by paritosh149** [charlieduong94/marko-path-router#30]
I have seen this feature in vue-router and would love to see similar feature in marko-path-router.
Please refer [https://router.vuejs.org/en/](url)

**Comment by charlieduong94** [comment]
Hello @paritosh149, great suggestion! In-component guards would also be a pretty neat feature to have. I'll try to get to this soon.

**Comment by charlieduong94** [comment]
@paritosh149 I just published version `0.7.1` which contains vue-like `beforeEach` and `afterEach` hooks. In-component guards are not supported yet, but I will have that up soon. For a very minimal example of how to use the hooks, you can take a look at the [marko-path-router-demo](https://github.com/charlieduong94/marko-path-router-demo) repo at [this commit](https://github.com/charlieduong94/marko-path-router-demo/commit/79ab6012f859239059c8b68743a25b20ee224845).
