### ISSUE TITLE
Pass data from parent to nested routes

### ISSUE THREAD

**Issue by IniZio** [charlieduong94/marko-path-router#32]
I have been using the nested route so that the parent will show a list of data, and the placeholder route will show the data detail. I read the docs but could not find the config to pass down data. Or is it recommended to use global store instead for this kind of data sharing?

**Comment by charlieduong94** [comment]
Using a global store is probably the easiest way to get data to your components. You can also opt in to using the [injectedInput](https://github.com/charlieduong94/marko-path-router#passing-data-to-route-components) field when rendering the router to share data with nested components.

**Comment by IniZio** [comment]
Thanks for the info! Really like the module :+1:
