### ISSUE TITLE
Navigation error on nested routes

### ISSUE THREAD

**Issue by jesse1983** [charlieduong94/marko-path-router#34]
Hello. I've just found a problem about navigation.

`src/index.marko`:

```marko
<!-- Routes -->
$ const routes = [{ path: '/admin', component: require('./components/home'), nestedRoutes: [
        { path: '/categories', component: require('./components/home/components/categories'), nestedRoutes: [
            { path: '/furniture', component: require('./components/home/components/categories/components/furniture') },        
            { path: '/beauty', component: require('./components/home/components/categories/components/beauty') },        
        ]},
        { path: '/users', component: require('./components/home/components/users') },
    ]
}];

<!-- HTML -->
div.my-app.container
  div.app-header
    h1.display-1 -- marko-path-router
    div.row
      div.col
        nav.nav.flex-column
          router-link class="nav-link" path='/admin' -- Home
          router-link class="nav-link" path='/admin/categories' -- Categories        
          nav.nav.flex-column
            router-link class="nav-link ml-3" path='/admin/categories/furniture' -- Furniture        
            router-link class="nav-link ml-3" path='/admin/categories/beauty' -- Beauty                    
          router-link class="nav-link" path='/admin/users' -- Users                 
      div.col-10 no-update
        router routes=routes initialRoute=window.location.pathname
```

`/admin`
![image](https://user-images.githubusercontent.com/2489514/37152483-41947d7e-22b8-11e8-855d-c8eeadd1117a.png)

Click on `Furniture`, for example `/admin/categories/furniture`:
![image](https://user-images.githubusercontent.com/2489514/37152556-7ef6eed6-22b8-11e8-9f7d-bb508bd8015d.png)

So far so good. 👍

---

## Bug

However, some navigations `only change navigation path`, but do not `render a component`.

Below are some navigation examples. Follow these sequences:

👍 `Home > Categories > Furniture > Beauty`
👍 `Home > Users` 
🚫 `Beauty > Categories > Home > Categories`  - Navigation path changed, but component not rendered
🚫 `Categories  > Home > Furniture`  - Navigation path changed, but component not rendered
👍 `Categories  > Home > Furniture > Users`  - When click on 'Users', the problem is solved (yes, it's very strange)

This code is available on [https://github.com/jesse1983/marko-path-router-issue](https://github.com/jesse1983/marko-path-router-issue). 

Feel free to download and make a pull request.

Does anybody can help me?

Thank you.

**Comment by charlieduong94** [comment]
Hi @jesse1983, thanks for reporting this issue and creating a repo that reproduces the problem (that's really awesome btw, thank you). I'll try to investigate this issue soon.

**Comment by lucianonetto** [comment]
I have the same problem.

**Comment by charlieduong94** [comment]
@lucianonetto thanks for letting me know and sorry for the delay/lack of updates, I've been busy lately. I did take an brief look at the issue and my initial impression is that this seems be related to changes to how components are rendered in the latest versions of marko.

I'll have more time to dedicate to debugging this issue this weekend, so you can expect some sort of update soonish.

**Comment by charlieduong94** [comment]
@lucianonetto @jesse1983 I published `0.7.3` which should fix the errors you have been seeing. Feel free to reopen this issue if you continue to see navigation issues.

**Comment by jesse1983** [comment]
@charlieduong94 Thank you for your attention.

I've installed the last version. It works on my repo, but on my project the bug's still there. 🤔 

I've been searching for differences between my project and the repo, and I found something: ***state changes on parent components***.

For example, the file `/src/components/home/index.marko` was:
```
div.admin
    if(input.renderBody)
        include(input.renderBody)
```
Then, I add state attributes and the bug shows up:

```
class {
    onCreate() {
        this.state = { name: '' }
    }
    onMount() {
        this.setState({ name: 'foo bar' });
    }
}

div.admin 
    h1 -- Welcome, ${ state.name }
    if(input.renderBody)
        include(input.renderBody)
```

I think that the problem only happens when I add `this.setState(...)` or `this.state = ...` on parent components.

The repo is updated. 

Thank you.

**Comment by charlieduong94** [comment]
Thanks for the feedback @jesse1983. I will look into this more soon.

**Comment by jesse1983** [comment]
One more tip: if I change method `onMount` to `onRender` for example, it's works.

**Comment by stefanobaldo** [comment]
@charlieduong94 Any update on this? I'm having the same problem.

**Comment by codingmaven** [comment]
@charlieduong94 

Do you have any update on this issue? I am also having same issue. Please let me know if you have any workaround for this issue.

**Comment by jesse1983** [comment]
Hi @charlieduong94 

I created other package to solve this problem: https://github.com/jesse1983/marko-router5

Can you test it?

**Comment by charlieduong94** [comment]
Cool! Sorry I haven't been doing a good job maintaining this project. I don't really use Marko as much as I used to. @jesse1983 I'll definitely test out your router though!
